import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppPage() {
  return (
    <div>
      <main>APP PAGE</main>
    </div>
  );
}
