import { MainContainer } from '@/components/container';
import { AppBar } from '@/components/navigation/app-nav/app-nav';
import AppToolbar from '@/components/navigation/app-toolbar';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'HOME',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <MainContainer maxWidth={false}>
      <AppBar>
        <AppToolbar />
      </AppBar>
    </MainContainer>
  );
}
