import LoginView from '@/sections/login';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function Loginpage() {
  return <LoginView />;
}
